### ISSUE TITLE
phasmerge: error message

### ISSUE THREAD

**Issue by sebel76** [atulkakrana/PHASIS#7]
Hi Atul,

I used your program PHASIS on my personal computer. I first performed the phasdetect with no problem. Then, I tried to used the phasmerge as explicated in your wiki tutorial. But, I got a message error.

Can you help me to resolve the problem? Please check the following error message:

MacBook-Pro-de-Sebastien:24-nt sebel76$ python3 phasmerge -mode merge -dir D0

#### Fn: checkLibs ###########################
--Python v3.0 or higher          : found

#### Fn: usagedata ###########################
Traceback (most recent call last):
  File "phasmerge.py", line 2704, in <module>
  File "phasmerge.py", line 2457, in main
  File "phasmerge.py", line 2439, in usagedata
  File "/Users/sebel76/miniconda3/lib/python3.5/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/sebel76/miniconda3/lib/python3.5/smtplib.py", line 335, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/sebel76/miniconda3/lib/python3.5/smtplib.py", line 306, in _get_socket
    self.source_address)
  File "/Users/sebel76/miniconda3/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/Users/sebel76/miniconda3/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

Do you have any recommendation to help me?

Many thanks and best regard,
Sébastien

**Comment by atulkakrana** [comment]
Aha - It's not an error. One of the required python libraries is missing, but the good news is that the missing library is only to prepare a debug report. So you can bypass the error by using `-debug` switch for `phasmerge` by simply adding  `-debug F` to your command, like this:

 `python3 phasmerge -mode merge -dir D0 -debug F`

Let me know if it solves your problem and sorry for the delay in responding to you.

Atul

**Comment by sebel76** [comment]
Hi Atul!

Thanks for your reply; I used it (-debug F), it solves the problem. I could make the analysis and obtained the output file of Phasmerge.

I used to perform the analysis using the gtf reference (from the gff corrected using the gffreads utility) and I got an error message. See the message receive:

#### Fn: gtfParser ###########################
Parsing '/Users/sebel76/NucleicAcid/1Morex_relase36/gff3/Hv_IBSC_PGSBv2.36.gtf' gtf file
Traceback (most recent call last):
  File "phasmerge.py", line 2704, in <module>
  File "phasmerge.py", line 2642, in main
  File "phasmerge.py", line 1839, in gtfParser2
IndexError: list index out of range

 
While I add a problem with the reference genome when I used the Phasdetect; I change the chromosome name (exemple: chr1 --> 1). The gtf was corrected also.

Have you a suggestion to solve the problem?

Thanks for your help!
Sébastien

**Comment by atulkakrana** [comment]
Hi Sebel,

Sorry for delay in response. I was travelling this week. Check if there is an empty line at the end of GTF file. If not then I might need to see your files. Can you compress and upload the genome and GTF file?

ATul

**Comment by atulkakrana** [comment]
Is this Barley genome? Did you downloaded genome and GTF from Phytozome? If yes, just send me the link to version that you have and I will test.

Atul

**Comment by sebel76** [comment]
Hi Atul,

Yes, this is the barley genome! I download the genome and the GTF on ensembl. You can download these files here : 

- genome : ftp://ftp.ensemblgenomes.org/pub/release-36/plants/fasta/hordeum_vulgare/dna/Hordeum_vulgare.Hv_IBSC_PGSB_v2.dna.toplevel.fa.gz

-GTF : ftp://ftp.ensemblgenomes.org/pub/release-36/plants/gtf/hordeum_vulgare/Hordeum_vulgare.Hv_IBSC_PGSB_v2.36.gtf.gz

Thanks to validate that for me! I wait your feedback to fix the problem.

Best,
Sébastien

**Comment by atulkakrana** [comment]
Hi Sebel - I will get back on this, it hasn't slipped out of my mind. Maybe you can send me link to your GTF file? Or paste your GFF READ command  that you used to make GTF file?

Atul

**Comment by sebel76** [comment]
Envoyé de mon iPhone

**Comment by sebel76** [comment]
Hi Atul,

Sorry for my delay of reply... I download my GTF file directly on the ensembl plant FTP site (ftp://ftp.ensemblgenomes.org/pub/release-36/plants/gtf/hordeum_vulgare/)!

I hope that you will find a solution for me; I am really interesting to used your pipeline!

Thanks and have a good day!

**Comment by sebel76** [comment]
Let's me know if you need anything else!

**Comment by sebel76** [comment]
Hi Atul,

Did you have the time to check the problem?

Thanks,
Sébastien

**Comment by wulouis** [comment]
Hi Autl,

I also got this package missing message and solved this problem by adding the " -debug F". Can I ask the name or how to install the missing package ? I would like to fix this error rather than typing "-debug F" every time lol... Thank you in advance for your help!

Best,
Louis
