### ISSUE TITLE
gtf file error

### ISSUE THREAD

**Issue by pokhrelsuresh** [atulkakrana/PHASIS#8]
Hi Atul,
I was trying to annotate the PHAS loci using gtf file as recommended in phasmerge wiki, it works for Arabidopsis, but doesn't work for the Flax. Here is the error:
#### Fn: gtfParser ###########################
Parsing 'Lusitatissimum_200_v1.0.gene_exons.gtf' gtf file
Total entries fetched from GTF file:262280

#### Fn: Annotate ############################
Preparing SQL table with GTF features
Feature table made with 262280 entries
Analysis for overlapping trans initialized
Traceback (most recent call last):
  File "phasmerge.py", line 2704, in <module>
  File "phasmerge.py", line 2651, in main
  File "phasmerge.py", line 1984, in overlapChecker
  File "phasmerge.py", line 2069, in overlapTrans
sqlite3.OperationalError: no such column: C7915081

The genomes and gff files are from phytozome. Can you please help to resolve the issue.

Thanks,
Suresh

**Comment by atulkakrana** [comment]
Suresh - Sorry for slow response, I am running busy with other things. Is this GTF file prepared as mentioned in wiki i.e. using GFFRead? See information here: https://github.com/atulkakrana/PHASIS/wiki/2.-phasmerge#misc

Atul

**Comment by pokhrelsuresh** [comment]
Yes, it was prepared by using gffread. It did for arabidopsis gff file and it works, means it annotated the phas loci using gff information.

Thanks,
Suresh

**Comment by atulkakrana** [comment]
Thanks for additional information. It's most likely a compatibility issue with "FLAX" GTF file. I will try to address it in PHASIS so that these minor formatting issues do not give error.

Atul
