### ISSUE TITLE
Phastrings error

### ISSUE THREAD

**Issue by Littlebigtham** [atulkakrana/PHASIS#9]
Hi Atul,

I used your program PHASIS.  I first performed the phasdetect and phasmerge (in merge and compare mode) with any problem.   But when I'm trying to run phastrings in the correct folder (were is located phasis.set, scripts, libraries, fasta miRNA file and phastmerge results) I obtain this error:

$ python3 phastrigs -mode auto -dir summary_09_05_16_59 -mir miRNAs_secuencias_para_buscar_blancos.fasta 

#### Fn: checkLibs ###########################
--sPARTA                         : found
--Bowtie2                        : found
--scipy                          : found
--numpy                          : found

#### Fn: Settings Reader #####################
User Input runType               : G
User Input reference             : /home/dinkova/sRNAs_analysis/phasis_final_genome_Zeamays_AGPv4/Zea_mays.AGPv4.dna.toplevel.fa
User Input Libs                  : ZmaEm1-1.txt,ZmaEm1-2.txt
User Input for phase length      : 21
User Input index location        : /home/dinkova/sRNAs_analysis/phasis_final_genome_Zeamays_AGPv4/index/Zea_mays.AGPv4.dna.toplevel.clean

#### Fn: memReader ##########################
collapse phase                   : 21
collapse pval                    : 1e-05
collapse file                    : ./summary_09_05_16_59/21PHAS_p1e-05_collapsed.txt
Creating dictionary of phased loci
This is the phaseList [-105, -84, -63, -42, -21, 0, 21, 42, 63, 84, 105]
#### Fn: PHAS Reader #########################
Head dictionary made with entries:8
Tail dictionary made with entries:8
** Strange, as you shouldn't have reached to this end of logic
** There is some problem validating correct reference location
** Reference file with clean headers located in /newdata/data2/homes/dinkova/sRNAs_analysis/phasis_final_genome_Zeamays_AGPv4/Zea_mays.AGPv4.dna.toplevel.clean.fa will be used
** You might face some issues in phastrigs run - Keep this message in mind

#### Fn: cacheGenome #########################
Traceback (most recent call last):
  File "phastrigs.py", line 1751, in <module>
    main()
  File "phastrigs.py", line 1630, in main
    coordsfile,extractseq   = extractSeq(reference,PHASList,phasbuff) ## runType aware
  File "phastrigs.py", line 371, in extractSeq
    fastaD,fastalenD = cacheGenome(fastaclean)
  File "phastrigs.py", line 969, in cacheGenome
    name        = ent[0].split()[0].strip()
IndexError: list index out of range

-------------------------------------------------------------------------------------------------------------------------------------------

I used this same location for reference and index to run phasdetect and phasmerge. my phasis.set file is this:

<<< Settings file for PHASIS >>>

<<< Mandatory Settings, see descriptions below >>>
@runType                = G
@reference              = /home/dinkova/sRNAs_analysis/phasis_final_genome_Zeamays_AGPv4/Zea_mays.AGPv4.dna.$
@userLibs               = ZmaEm1-1.txt,ZmaEm1-2.txt
@libFormat              = T
@phase          = 21

<<< Optional Settings, leave empty to make index on fly and reuse, value in text>>>
@index          = /home/dinkova/sRNAs_analysis/phasis_final_genome_Zeamays_AGPv4/index/Zea_mays.AGPv4.dna.to$

<<< Advanced Settings, value in text>>>
@minDepth               = 3
@clustBuffer    = 300
@mismat         = 0

<<<Settings Help>>>
<@runType               - G: Running on whole genome | T: running on transcriptome | S: running on scaffolde$
<@reference     - If @runType = ‘G’ then genome FASTA |  @runType = ’S’ or ’T’ then your scaffolds or transc$
<@userLibs              - Specify library IDs in comma separated format to fetch data. Used only if @fetchLi$
<@libFormat     - Specify the sRNA library format. F: FASTA Format | T: Tag count format>
<@phase         - Desired phase to use for prediction. 21 for 21 nt PHAS | 24 for 24 nt PHAS>
<@index         - If bowtie index exist already provide the path and index suffix. If not, then leave blank,$
<@minDepth	- Minimum depth of sRNA to be considered for p-value computation>
<@clustBuffer   - Minimum distance between two clusters>
<@mismat                - Number of mismatches allowed between sRNA and reference for mapping>

<<<END>>>
<<<v3.0>>>
<<<Author: kakrana@gmail.com>>>

------------------------------------------------------------------------------------------------------------------------------------------

Can you help me with that?

I really appreciate your answer :)

Thamara

**Comment by phase** [comment]
oof, put @'s in code blocks you don't tag people

**Comment by atulkakrana** [comment]
Hi Littlebigtham,

Sorry for the issue that you are facing. Could you please paste content of your `phasis.mem` file? Just paste the settings part and not the help section towards the bottom.

Atul

**Comment by Littlebigtham** [comment]
Thanks Atul,

The phasis.mem contain:

timestamp:09_05_14_50
genomehash:a8d3069cd9554885670848cc3df185cb
index:/newdata/data2/homes/dinkova/sRNAs_analysis/phasis_final_genome_Zeamays_AGPv4/index/Zea_mays.AGPv4.dna.toplevel.clean
indexhash:b3ff8bc5b633ce38484d9a88056768b4

**Comment by atulkakrana** [comment]
Sorry - I meant `phasis.set` file. Atul

**Comment by Littlebigtham** [comment]
runType                = G
reference              = /home/dinkova/sRNAs_analysis/phasis_final_genome_Zeamays_AGPv4/Zea_mays.AGPv4.dna.toplevel.fa
userLibs               = ZmaEm1-1.txt,ZmaEm1-2.txt
libFormat              = T
phase          = 21

<<< Optional Settings, leave empty to make index on fly and reuse, value in text>>>
index          = /home/dinkova/sRNAs_analysis/phasis_final_genome_Zeamays_AGPv4/index/Zea_mays.AGPv4.dna.toplevel.clean

<<< Advanced Settings, value in text>>>
minDepth               = 3
clustBuffer    = 300
mismat         = 0

**Comment by sebel76** [comment]
Hi Atul (and Thamara),

I obtained the same message error when using phastrings...

Is any solution exist to resolve the problem? 

I will really obtained a completed analysis from phasdetect.py to phastrings.py and complete my core analysis.

Is one of you can help me with that?

I will really appreciate an answer :)

Thanks,
Sébastien

**Comment by atulkakrana** [comment]
Hi Thamara and Sebastian - I am very sorry for not responding to your issues; I am running very busy these days and not getting time to check the script. I will see if I can resolve it this week; it's in my mind. Atul

**Comment by sebel76** [comment]
Please, will you check the bug code...?
